//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lists.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lists.Constants.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///IF NOT EXISTS(SELECT 1 
        ///			  FROM Emails 
        ///			  WHERE body = @body
        ///			  AND to_email = @to_email
        ///			  AND sent = 0) 
        ///    BEGIN
        ///	INSERT INTO Emails 
        ///	VALUES (@to_email, @body, @subject, 0, @createdOn);
        ///	END
        ///END.
        /// </summary>
        public static string AddToEmailQueue {
            get {
                return ResourceManager.GetString("AddToEmailQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO list_items  
        ///(list_id, list_item_content, created_on, deleted, created_by, last_modified_on, last_modified_by, grocery_price, quantity, purchased)
        ///SELECT @list_id as list_id,
        ///	   li.list_item_content as list_item_content,
        ///	   @created_on as created_on,
        ///	   0 as deleted, 
        ///	   @created_by as created_by, 
        ///	   @last_modified_on as last_modified_on, 
        ///	   @last_modified_by as last_modified_by,
        ///	   MAX(li.grocery_price) as grocery_price, 
        ///	   1 as quantity,
        ///	   0 as purchased
        ///FROM List_item [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AutoPopulateGroceryList {
            get {
                return ResourceManager.GetString("AutoPopulateGroceryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM amazon_items WHERE item_id = @item_id.
        /// </summary>
        public static string DeleteAmazonItemById {
            get {
                return ResourceManager.GetString("DeleteAmazonItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE attachment SET deleted = 1 WHERE attachment_id = @attachment_id;.
        /// </summary>
        public static string DeleteAttachmentById {
            get {
                return ResourceManager.GetString("DeleteAttachmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE attachment_data SET deleted = 1 WHERE attachment_data_id = @attachment_data_id;.
        /// </summary>
        public static string DeleteAttachmentDataById {
            get {
                return ResourceManager.GetString("DeleteAttachmentDataById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM average_grocery_prices WHERE grocery_item_name = @grocery_item_name.
        /// </summary>
        public static string DeleteAverageGroceryListItem {
            get {
                return ResourceManager.GetString("DeleteAverageGroceryListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM list_item_claimed_by WHERE person_id = @person_id AND list_item_id = @list_item_id.
        /// </summary>
        public static string DeleteClaimer {
            get {
                return ResourceManager.GetString("DeleteClaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE comments SET deleted = 1 WHERE comment_id = @comment_id.
        /// </summary>
        public static string DeleteCommentById {
            get {
                return ResourceManager.GetString("DeleteCommentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM list_editors WHERE list_id = @list_id AND editor_id = @editor_id.
        /// </summary>
        public static string DeleteEditorByListIdPersonId {
            get {
                return ResourceManager.GetString("DeleteEditorByListIdPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE lists_new 
        ///SET deleted = 1 
        ///WHERE DATEADD(week, 1, created_on) &gt; GETDATE() 
        ///AND EXISTS (SELECT 1 
        ///			FROM persons p (NOLOCK)
        ///			WHERE p.is_guest = 1 
        ///			AND p.deleted = 0 
        ///			AND p.person_id = owner_id) 
        ///AND deleted = 0.
        /// </summary>
        public static string DeleteExpiredGuestLists {
            get {
                return ResourceManager.GetString("DeleteExpiredGuestLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM list_access_request WHERE id = @id.
        /// </summary>
        public static string DeleteListAccessRequest {
            get {
                return ResourceManager.GetString("DeleteListAccessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE lists_new SET deleted = 1 WHERE list_id = @list_id.
        /// </summary>
        public static string DeleteListById {
            get {
                return ResourceManager.GetString("DeleteListById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE list_items SET deleted = 1 WHERE list_item_id = @list_item_id.
        /// </summary>
        public static string DeleteListItemById {
            get {
                return ResourceManager.GetString("DeleteListItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE persons SET deleted = 1 WHERE person_id = @person_id.
        /// </summary>
        public static string DeletePersonById {
            get {
                return ResourceManager.GetString("DeletePersonById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM quick_add_grocery_item WHERE personid = @person_id AND user_entered = 0.
        /// </summary>
        public static string DeleteQuickAddGroceryItems {
            get {
                return ResourceManager.GetString("DeleteQuickAddGroceryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM quick_add_grocery_item WHERE item_id = @item_id.
        /// </summary>
        public static string DeleteQuickAddItemById {
            get {
                return ResourceManager.GetString("DeleteQuickAddItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM list_viewers WHERE list_id = @list_id AND person_id = @person_id.
        /// </summary>
        public static string DeleteViewerByListIdPersonId {
            get {
                return ResourceManager.GetString("DeleteViewerByListIdPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM persons WHERE username = @username.
        /// </summary>
        public static string DoesUsernameExist {
            get {
                return ResourceManager.GetString("DoesUsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM site_messages (nolock) WHERE GETDATE() &gt;= show_from AND GETDATE() &lt;= show_to.
        /// </summary>
        public static string GetActiveSiteMessages {
            get {
                return ResourceManager.GetString("GetActiveSiteMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT i.list_item_content
        ///FROM list_items i
        ///JOIN lists_new l
        ///ON l.list_id = i.list_id
        ///AND l.list_type = 10003.
        /// </summary>
        public static string GetAllGroceryItems {
            get {
                return ResourceManager.GetString("GetAllGroceryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM lists_new WHERE deleted = 0.
        /// </summary>
        public static string GetAllLists {
            get {
                return ResourceManager.GetString("GetAllLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM list_types.
        /// </summary>
        public static string GetAllListTypes {
            get {
                return ResourceManager.GetString("GetAllListTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT person_id FROM persons WHERE deleted = 0.
        /// </summary>
        public static string GetAllPersonIds {
            get {
                return ResourceManager.GetString("GetAllPersonIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM amazon_items WHERE item_name = @item_name.
        /// </summary>
        public static string GetAmazonItemByName {
            get {
                return ResourceManager.GetString("GetAmazonItemByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM amazon_items WHERE item_name LIKE &apos;%{0}%&apos;.
        /// </summary>
        public static string GetAmazonItemsByName {
            get {
                return ResourceManager.GetString("GetAmazonItemsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM attachments WHERE attachment_id = @attachment_id AND deleted = 0.
        /// </summary>
        public static string GetAttachmentById {
            get {
                return ResourceManager.GetString("GetAttachmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM attachment_data WHERE attachment_data_id = @attachment_data_id.
        /// </summary>
        public static string GetAttachmentDataById {
            get {
                return ResourceManager.GetString("GetAttachmentDataById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM  attachments WHERE list_item_id = @list_item_id AND deleted = 0.
        /// </summary>
        public static string GetAttachmentsByListItemId {
            get {
                return ResourceManager.GetString("GetAttachmentsByListItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select AVG(i.grocery_price)
        ///from list_items i (nolock)
        ///join lists_new l (nolock)
        ///on l.list_id = i.list_id 
        ///and l.list_type = 10003
        ///where i.list_item_content like &apos;%{0}%&apos;.
        /// </summary>
        public static string GetAverageGroceryPrice {
            get {
                return ResourceManager.GetString("GetAverageGroceryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM cell_phone_providers WHERE provider_id = @provider_id.
        /// </summary>
        public static string GetCellPhoneProviderById {
            get {
                return ResourceManager.GetString("GetCellPhoneProviderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM cell_phone_providers.
        /// </summary>
        public static string GetCellPhoneProviders {
            get {
                return ResourceManager.GetString("GetCellPhoneProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM change_control WHERE change_id = @change_id.
        /// </summary>
        public static string GetChangeControlById {
            get {
                return ResourceManager.GetString("GetChangeControlById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM comments WHERE comment_id = @comment_id and deleted = 0.
        /// </summary>
        public static string GetCommentById {
            get {
                return ResourceManager.GetString("GetCommentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM comments WHERE list_item_id = @list_item_id and deleted = 0.
        /// </summary>
        public static string GetCommentsByListItemId {
            get {
                return ResourceManager.GetString("GetCommentsByListItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sales_tax_ip_address WHERE entry_id = @entry_id.
        /// </summary>
        public static string GetIpAddressSalesTaxById {
            get {
                return ResourceManager.GetString("GetIpAddressSalesTaxById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 * FROM sales_tax_ip_address WHERE ip_address = @ip_address.
        /// </summary>
        public static string GetIpAddressSalesTaxByIp {
            get {
                return ResourceManager.GetString("GetIpAddressSalesTaxByIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 * FROM sales_tax_ip_address WHERE zip_code = @zip_code.
        /// </summary>
        public static string GetIpAddressSalesTaxByZipCode {
            get {
                return ResourceManager.GetString("GetIpAddressSalesTaxByZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM sales_tax_ip_address WHERE sales_tax IS NULL.
        /// </summary>
        public static string GetIpAddressWithNoSalesTax {
            get {
                return ResourceManager.GetString("GetIpAddressWithNoSalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT* FROM sales_tax_ip_address WHERE sales_tax IS NOT NULL.
        /// </summary>
        public static string GetIpAddressWithSalesTax {
            get {
                return ResourceManager.GetString("GetIpAddressWithSalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM list_access_request WHERE id = @id.
        /// </summary>
        public static string GetListAccessRequestById {
            get {
                return ResourceManager.GetString("GetListAccessRequestById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM list_access_request WHERE list_id = @list_id.
        /// </summary>
        public static string GetListAccessRequestByListId {
            get {
                return ResourceManager.GetString("GetListAccessRequestByListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM lists_new WHERE list_id = @list_id AND deleted = 0.
        /// </summary>
        public static string GetListById {
            get {
                return ResourceManager.GetString("GetListById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM lists_new WHERE share_id = @share_id AND deleted = 0 .
        /// </summary>
        public static string GetListByShareId {
            get {
                return ResourceManager.GetString("GetListByShareId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT editor_id FROM list_editors WHERE list_id = @list_id.
        /// </summary>
        public static string GetListEditorsByListId {
            get {
                return ResourceManager.GetString("GetListEditorsByListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT distinct l.* FROM lists_new l JOIN list_editors lv on lv.list_id = l.list_id WHERE (lv.editor_id = @person_id OR l.owner_id = @person_id) AND l.deleted = 0.
        /// </summary>
        public static string GetListEditsByPersonId {
            get {
                return ResourceManager.GetString("GetListEditsByPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM list_items WHERE list_item_id = @list_item_id AND deleted = 0.
        /// </summary>
        public static string GetListItemById {
            get {
                return ResourceManager.GetString("GetListItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT person_id FROM list_item_claimed_by WHERE list_item_id = @list_item_id.
        /// </summary>
        public static string GetListItemClaimersByListItemId {
            get {
                return ResourceManager.GetString("GetListItemClaimersByListItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM list_items WHERE list_id = @list_id AND deleted = 0.
        /// </summary>
        public static string GetListItemsByListId {
            get {
                return ResourceManager.GetString("GetListItemsByListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM lists_new WHERE owner_id = @person_id and deleted = 0.
        /// </summary>
        public static string GetListsByOwnerId {
            get {
                return ResourceManager.GetString("GetListsByOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT distinct l.* FROM lists_new l JOIN list_viewers lv on lv.list_id = l.list_id WHERE (lv.person_id = @person_id OR l.owner_id = @person_id) AND l.deleted = 0.
        /// </summary>
        public static string GetListsViewsByPersonId {
            get {
                return ResourceManager.GetString("GetListsViewsByPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM list_types WHERE list_type_id = @list_type_id.
        /// </summary>
        public static string GetListTypeById {
            get {
                return ResourceManager.GetString("GetListTypeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT person_id FROM list_viewers WHERE list_id = @list_id.
        /// </summary>
        public static string GetListViewersByListId {
            get {
                return ResourceManager.GetString("GetListViewersByListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM persons WHERE person_id = @person_id.
        /// </summary>
        public static string GetPersonById {
            get {
                return ResourceManager.GetString("GetPersonById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.* FROM persons p JOIN person_pattern pp ON pp.person_id = p.person_id AND pp.pattern = @pattern WHERE p.username= @username.
        /// </summary>
        public static string GetPersonByUsernameAndPattern {
            get {
                return ResourceManager.GetString("GetPersonByUsernameAndPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM person_contact_information ci LEFT JOIN cell_phone_providers cpp ON ci.cell_phone_provider = cpp.provider_id WHERE ci.person_id = @person_id.
        /// </summary>
        public static string GetPersonContactInfoByPersonId {
            get {
                return ResourceManager.GetString("GetPersonContactInfoByPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.person_id 
        ///FROM persons p 
        ///JOIN person_contact_information c 
        ///ON p.person_id = c.person_id
        /// WHERE p.username = @username 
        /// AND c.email = @email.
        /// </summary>
        public static string GetPersonIdByEmailAndUsername {
            get {
                return ResourceManager.GetString("GetPersonIdByEmailAndUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM lists_new WHERE is_public = 1 AND deleted = 0.
        /// </summary>
        public static string GetPublicLists {
            get {
                return ResourceManager.GetString("GetPublicLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Emails WHERE sent = 0 ORDER BY createdOn ASC.
        /// </summary>
        public static string GetQueuedEmails {
            get {
                return ResourceManager.GetString("GetQueuedEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM quick_add_grocery_item WHERE personid = @personid AND user_entered = @user_entered.
        /// </summary>
        public static string GetQuickAddGroceryItems {
            get {
                return ResourceManager.GetString("GetQuickAddGroceryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM quick_add_grocery_item WHERE item_id = @item_id.
        /// </summary>
        public static string GetQuickItemById {
            get {
                return ResourceManager.GetString("GetQuickItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 average_price FROM average_grocery_prices WHERE grocery_item_name =@grocery_item_name.
        /// </summary>
        public static string GetSaveAverageGroceryPrice {
            get {
                return ResourceManager.GetString("GetSaveAverageGroceryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT state_code FROM states WHERE state_name = @state_name.
        /// </summary>
        public static string GetStateCodeByStateName {
            get {
                return ResourceManager.GetString("GetStateCodeByStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 10 i.list_item_content, COUNT(i.list_item_content)
        ///FROM list_items i 
        ///JOIN lists_new l
        ///ON l.list_id = i.list_id
        ///AND l.list_type = 10003
        ///WHERE l.owner_id = @person_id
        ///GROUP BY i.list_item_content 
        ///ORDER BY COUNT(i.list_item_content) DESC.
        /// </summary>
        public static string GetTop10GroceryItems {
            get {
                return ResourceManager.GetString("GetTop10GroceryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO amazon_items (item_link, item_name) VALUES (@item_link, @item_name).
        /// </summary>
        public static string InsertAmazonItem {
            get {
                return ResourceManager.GetString("InsertAmazonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO site_messages VALUES (@text, @show_from, @show_to, @type).
        /// </summary>
        public static string InsertSiteMessage {
            get {
                return ResourceManager.GetString("InsertSiteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE change_control SET used = 1 WHERE change_id = @change_id.
        /// </summary>
        public static string MarkChangeControlUsed {
            get {
                return ResourceManager.GetString("MarkChangeControlUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Emails SET sent = 1 WHERE id = @id.
        /// </summary>
        public static string MarkEmailAsSent {
            get {
                return ResourceManager.GetString("MarkEmailAsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT list_id FROM lists_new WHERE deleted = 0 AND list_id &lt; @PreviousListId ORDER BY list_id DESC.
        /// </summary>
        public static string NextListsExist {
            get {
                return ResourceManager.GetString("NextListsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP {0} list_id FROM lists_new WHERE deleted = 0 AND list_id &gt; @PreviousListId ORDER BY list_id DESC.
        /// </summary>
        public static string PreviousListsExist {
            get {
                return ResourceManager.GetString("PreviousListsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE person_pattern SET pattern = @pattern WHERE person_id = (SELECT person_id FROM persons WHERE username = @username).
        /// </summary>
        public static string ReplacePattern {
            get {
                return ResourceManager.GetString("ReplacePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO attachments VALUES (@attachment_type, @attachment_description, @attachment_data_id, @list_item_id, 0);SELECT attachment_id FROM attachments WHERE attachment_id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SaveAttachment {
            get {
                return ResourceManager.GetString("SaveAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO attachment_data VALUES (@attachment_data, @attachment_data_mime);SELECT attachment_data_id FROM attachment_data WHERE attachment_data_id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SaveAttachmentData {
            get {
                return ResourceManager.GetString("SaveAttachmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO average_grocery_prices VALUES (@grocery_item_name, @average_price).
        /// </summary>
        public static string SaveAverageGroceryListItem {
            get {
                return ResourceManager.GetString("SaveAverageGroceryListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO change_control VALUES(@change_id, 0).
        /// </summary>
        public static string SaveChangeControl {
            get {
                return ResourceManager.GetString("SaveChangeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO list_item_claimed_by (person_id, list_item_id) VALUES (@person_id, @list_item_id).
        /// </summary>
        public static string SaveClaimer {
            get {
                return ResourceManager.GetString("SaveClaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO comments VALUES (@text, @created_by, @list_item_id, @created_on, 0, @is_whisper); SELECT comment_id FROM comments WHERE comment_id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SaveComment {
            get {
                return ResourceManager.GetString("SaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO person_contact_information VALUES (@person_id, @email, @cell_phone_number, @cell_phone_provider);.
        /// </summary>
        public static string SaveContactInformation {
            get {
                return ResourceManager.GetString("SaveContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO person_pattern VALUES ((SELECT person_id FROM persons WHERE username = @username), @pattern).
        /// </summary>
        public static string SaveCredentials {
            get {
                return ResourceManager.GetString("SaveCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO list_editors VALUES (@list_id, @editor_id).
        /// </summary>
        public static string SaveEditor {
            get {
                return ResourceManager.GetString("SaveEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO list_items (list_id, list_item_content, created_on, deleted, created_by, last_modified_by, grocery_price) VALUES(@list_id, @list_item_content, @created_on, 0, @created_by, @last_modified_on, @last_modified_by, @grocery_price); SELECT list_item_id FROM list_items WHERE list_item_id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SaveGroceryListItem {
            get {
                return ResourceManager.GetString("SaveGroceryListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO sales_tax_ip_address VALUES (@ip_address, @zip_code, @sales_tax); SELECT entry_id FROM sales_tax_ip_address WHERE entry_id = SCOPE_IDENTITY().
        /// </summary>
        public static string SaveIpAddressSalesTax {
            get {
                return ResourceManager.GetString("SaveIpAddressSalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO lists_new VALUES (@list_name, @list_type, 0, @created_on, @created_by, @owner_id, @expires_on, @is_public, @share_id, @is_private);SELECT list_id FROM lists_new WHERE list_id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SaveList {
            get {
                return ResourceManager.GetString("SaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO list_access_request VALUES (@person_id, @list_id, @access_type); SELECT id FROM list_access_request WHERE id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SaveListAccessRequest {
            get {
                return ResourceManager.GetString("SaveListAccessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO list_items VALUES(@list_id, @list_item_content, @created_on, 0, @created_by, @last_modified_on, @last_modified_by, @grocery_price, @quantity, @purchased, @prayer_count, @url, @pro_con_type, @pro_con_weight); SELECT list_item_id FROM list_items WHERE list_item_id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SaveListItem {
            get {
                return ResourceManager.GetString("SaveListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO persons VALUES (@f_name, @m_name, @l_name, @username, 0, @is_guest, 0); SELECT person_id FROM persons WHERE person_id = (SELECT SCOPE_IDENTITY());.
        /// </summary>
        public static string SavePerson {
            get {
                return ResourceManager.GetString("SavePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO quick_add_grocery_item VALUES (@quick_grocery_item, @person_id, @user_entered, 0); SELECT item_id FROM quick_add_grocery_item WHERE item_id = SCOPE_IDENTITY().
        /// </summary>
        public static string SaveQuickAddGroceryItem {
            get {
                return ResourceManager.GetString("SaveQuickAddGroceryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO list_viewers VALUES (@list_id, @person_id).
        /// </summary>
        public static string SaveViewer {
            get {
                return ResourceManager.GetString("SaveViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT distinct person_id, f_name, l_name FROM persons WHERE f_name LIKE &apos;%@query%&apos; OR l_name LIKE &apos;%@query%&apos;.
        /// </summary>
        public static string SearchPersonByName {
            get {
                return ResourceManager.GetString("SearchPersonByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE lists_new SET deleted = 0 WHERE list_id = @list_id.
        /// </summary>
        public static string UndeleteListById {
            get {
                return ResourceManager.GetString("UndeleteListById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE list_items SET deleted = 0 WHERE list_item_id = @list_item_id.
        /// </summary>
        public static string UndeleteListItemById {
            get {
                return ResourceManager.GetString("UndeleteListItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE amazon_items SET item_name = @item_name, item_link = @item_link where item_id = @item_id.
        /// </summary>
        public static string UpdateAmazonItemById {
            get {
                return ResourceManager.GetString("UpdateAmazonItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE attachments SET attachment_type = @attachment_type, attachment_description = @attachment_description, attachment_data_id = @attachment_data_id, list_item_id = @list_item_id WHERE attachment_id = @attachment_id;.
        /// </summary>
        public static string UpdateAttachmentById {
            get {
                return ResourceManager.GetString("UpdateAttachmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE attachment_data SET attachment_data = @attachment_data, attachment_data_mime = @attachment_data_mime WHERE attachment_data_id = @attachment_data_id;.
        /// </summary>
        public static string UpdateAttachmentDataById {
            get {
                return ResourceManager.GetString("UpdateAttachmentDataById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE person_contact_information SET email = @email, cell_phone_number = @cell_phone_number, cell_phone_provider = @cell_phone_provider WHERE person_id = @person_id.
        /// </summary>
        public static string UpdateContactInformationByPersonId {
            get {
                return ResourceManager.GetString("UpdateContactInformationByPersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE sales_tax_ip_address SET ip_address = @ip_address, zip_code = @zip_code, sales_tax = @sales_tax WHERE entry_id = @entry_id.
        /// </summary>
        public static string UpdateIpAddressSalesTax {
            get {
                return ResourceManager.GetString("UpdateIpAddressSalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE lists_new SET list_name = @list_name, list_type = @list_type, owner_id = @owner_id, expires_on = @expires_on, is_public = @is_public, share_id = @share_id, is_private = @is_private WHERE list_id = @list_id.
        /// </summary>
        public static string UpdateListById {
            get {
                return ResourceManager.GetString("UpdateListById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE list_items SET list_id = @list_id, list_item_content = @list_item_content, last_modified_by = @last_modified_by, last_modified_on = @last_modified_on, grocery_price =@grocery_price, quantity = @quantity, purchased = @purchased, prayer_count = @prayer_count, url = @url, pro_con_weight = @pro_con_weight, pro_con_type=@pro_con_type WHERE list_item_id = @list_item_id.
        /// </summary>
        public static string UpdateListItemById {
            get {
                return ResourceManager.GetString("UpdateListItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE persons SET f_name = @f_name, m_name = @m_name, l_name = @l_name, username = @username, is_guest = @is_guest WHERE person_id = @person_id.
        /// </summary>
        public static string UpdatePersonById {
            get {
                return ResourceManager.GetString("UpdatePersonById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE quick_add_grocery_item SET is_hidden = @is_hidden WHERE item_id = @item_id.
        /// </summary>
        public static string UpdateQuickAddItem {
            get {
                return ResourceManager.GetString("UpdateQuickAddItem", resourceCulture);
            }
        }
    }
}
